base_url = "https://kaiwolfram.com"
title = "Kai Wolfram"
default_language = "en"
highlight_code = true
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
    { name = "tags", feed = true, paginate_by = 10 },
]
compile_sass = true
build_search_index = true
ignored_content = []
extra_syntaxes = []

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
navbar_items = [
    { code = "en", nav_items = [
        { url = "$BASE_URL", name = "Home" },
        { url = "$BASE_URL/projects", name = "Projects" },
        { url = "$BASE_URL/opensource", name = "Opensource" },
        { url = "$BASE_URL/posts", name = "Posts" },
        { url = "$BASE_URL/tags", name = "Tags" },
    ] },
]

[extra.author]
name = "Kai Wolfram"
avatar = "/images/torro.jpg"

[extra.social]
github = "KaiWitt"
keybase = "kaiwitt"
email = "kaiwitt@protonmail.com"
bitcoin = "bc1qrhxputc6t45w8p2j8k7ke72a9zgqgt3q5gkgat"

