baseURL = 'http://www.kaiwolfram.com/'
languageCode = 'en-us'
title = 'Kai Wolfram'

[params]
colortheme = "classic" # dark, light, white, or classic
description = "Software developer with an interest in Bitcoin, economics and freedom."
copyright = "Kai Wolfram"
rss = true
tagsOverview = false
tocInline = true
showAllPostsOnHomePage = false
postsOnHomePage = 5
mainSectionTitle = "Posts"
mainSection = "posts"
showProjectsList = true
projectsUrl = "https://github.com/KaiWitt"
showOpensourceList = true
opensourceUrl = "https://github.com/KaiWitt"

[[params.social]]
  name = "github"
  link = "https://github.com/KaiWitt"
[[params.social]]
  name = "keybase"
  link = "https://keybase.io/kaiwitt"
[[params.social]]
  name = "email"
  link = "kaiwitt@protonmail.com"
[[params.social]]
  name = "bitcoin"
  link = "bc1qrhxputc6t45w8p2j8k7ke72a9zgqgt3q5gkgat"


[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About me"
url = "/about"
weight = 3

# Default code highlight
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4