baseURL = 'https://www.kaiwolfram.com/'
languageCode = 'en-us'
title = 'Kai Wolfram'

[params]
colortheme = "kai" # dark, light, white, classic or kai
description = "I'm a software developer with an interest in economics and freedom enhancing tools."
copyright = "Kai Wolfram"
rss = true
tagsOverview = false
tocInline = true
showAllPostsOnHomePage = false
postsOnHomePage = 5
showMainSection = false
mainSectionTitle = "Posts"
mainSection = "posts"
showProjectsList = false
projectsUrl = "https://github.com/KaiWitt"
showOpensourceList = false
opensourceUrl = "https://github.com/KaiWitt"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/kai_wolfram"
[[params.social]]
  name = "github"
  link = "https://github.com/KaiWitt"
[[params.social]]
  name = "keybase"
  link = "https://keybase.io/kaiwitt"
[[params.social]]
  name = "email"
  link = "kaiwolfram@protonmail.com"


[[menu.main]]
name = "Home"
url = "/"
weight = 1
# [[menu.main]]
# name = "Posts"
# url = "/posts"
# weight = 2
[[menu.main]]
name = "About"
url = "/about"
weight = 3

# Default code highlight
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4